version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /Users/whitetree/Code/SQL/etc/conf/my.cnf:/etc/mysql/my.cnf
      - /Users/whitetree/Code/SQL/etc/logs:/logs
      - /Users/whitetree/Code/SQL/etc/data:/mysql_data
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network
  big-event:
    # build: ./Dockerfile
    image: big-event:4.0
    container_name: big-event-back
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      my-network:
        aliases:
          - mydb
networks:
  my-network:
    driver: bridge
