version: "3"
services:
  big-event:
    build: .
    container_name: big-event-back
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/big_event?allowPublicKeyRetrieval=true
      - spring.data.redis.host=redis
    depends_on:
      - mysqldb
    networks:
      - my-network

  mysqldb:
    image: mysql
    restart: always
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - /Users/whitetree/Code/SQL/etc/conf/my.cnf:/etc/mysql/my.cnf
      - /Users/whitetree/Code/SQL/etc/logs:/logs
      - /Users/whitetree/Code/SQL/etc/data:/mysql_data
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network

  #  add redis container to same network
  redis:
    image: redis
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network
    

networks:
  my-network:
    driver: bridge
